---
title: "Learning Algorithm Visualization"
author: "Kapil Arun Garg"
date: "June 9, 2015"
output: html_document
---

This document will be used to visualize the data we have compiled though various learning algorithms.

Load Libraries and necessary functons
```{r Libraries and Functions, echo = FALSE}
library(data.table)
library(lubridate)
library(reshape2)
library(ggplot2)
library(grid)
library(dplyr)
library(TTR)
library(scales)
library(cluster)
library(extrafont)
loadfonts()
options(digits = 15)
options(scipen = 100)

###Functions###

##SOURCED FROM COOKBOOK FOR R: http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_%28ggplot2%29/ ##
Multiplot <- function(..., plotlist = NULL, file, cols = 1, layout = NULL)
{
  require(grid)
  
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  if (is.null(layout)) {
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots == 1) {
    print(plots[[1]])
    
  } else {
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    for (i in 1:numPlots) {
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

##SOURCED FROM: http://rpubs.com/kohske/dual_axis_in_ggplot2 ##
MultipleAxes <- function(plot1, plot2)
{
  # extract gtable but create the plots first
  g1 <- ggplot_gtable(ggplot_build(plot1))
  g2 <- ggplot_gtable(ggplot_build(plot2))
  
  # overlap the panel of 2nd plot on that of 1st plot
  pp <- c(subset(g1$layout, name == "panel", se = t:r))
  g <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, pp$l, pp$b, pp$l)
  
  # axis tweaks
  ia <- which(g2$layout$name == "axis-l")
  ga <- g2$grobs[[ia]]
  ax <- ga$children[[2]]
  ax$widths <- rev(ax$widths)
  ax$grobs <- rev(ax$grobs)
  ax$grobs[[1]]$x <- ax$grobs[[1]]$x - unit(1, "npc") + unit(0.15, "cm")
  g <- gtable_add_cols(g, g2$widths[g2$layout[ia, ]$l], length(g$widths) - 1)
  g <- gtable_add_grob(g, ax, pp$t, length(g$widths) - 1, pp$b)
  
  # add y axis label on right
  ia2 <- which(g2$layout$name == "ylab")
  ga2 <- g2$grobs[[ia2]]
  ga2$rot <- -90
  g <- gtable_add_cols(g, g2$widths[g2$layout[ia2, ]$l], length(g$widths) - 1)
  g <- gtable_add_grob(g, ga2, pp$t, length(g$widths) - 1, pp$b)
  
  #Draw graph
  #grid.draw(g)
  return(g)
}

#Function to align ggplot objects 
##SOURCED FROM baptiste: http://stackoverflow.com/questions/13294952/left-align-two-graph-edges-ggplot/13295880#13295880 ##
RbindGtableMax <- function(...){
  gtl <- list(...)
  stopifnot(all(sapply(gtl, is.gtable)))
  Bind2 <- function (x, y) 
  {
    stopifnot(ncol(x) == ncol(y))
    if (nrow(x) == 0) 
      return(y)
    if (nrow(y) == 0) 
      return(x)
    y$layout$t <- y$layout$t + nrow(x)
    y$layout$b <- y$layout$b + nrow(x)
    x$layout <- rbind(x$layout, y$layout)
    x$heights <- gtable:::insert.unit(x$heights, y$heights)
    x$rownames <- c(x$rownames, y$rownames)
    x$widths <- grid::unit.pmax(x$widths, y$widths)
    x$grobs <- append(x$grobs, y$grobs)
    x
  }
  
  Reduce(Bind2, gtl)
}

CbindGtableMax <- function(...){
  gtl <- list(...)
  stopifnot(all(sapply(gtl, is.gtable)))
  Bind2 <- function (x, y) 
  {
    stopifnot(nrow(x) == nrow(y))
    if (ncol(x) == 0) 
      return(y)
    if (ncol(y) == 0) 
      return(x)
    y$layout$l <- y$layout$l + ncol(x)
    y$layout$r <- y$layout$r + ncol(x)
    x$layout <- rbind(x$layout, y$layout)
    x$widths <- gtable:::insert.unit(x$widths, y$widths)
    x$colnames <- c(x$colnames, y$colnames)
    x$heights <- grid::unit.pmax(x$heights, y$heights)
    x$grobs <- append(x$grobs, y$grobs)
    x
  }
  Reduce(Bind2, gtl)
}

#Custom tranformation for an nth-root axis
NthrootTrans <- function(base = 2)
{
  trans <- function(x) x^(1/base)
  inv <- function(x) x^base
  trans_new(paste0("nthroot", format(base)), trans, inv, domain = c(0, Inf))
}

#Rescale data to lower and upper values (default: 0-1) scale based on data sets min and max
CustomRange <- function(x, lower = 0, upper = 1)
{
  return(((x - min(x)) * ((upper - lower)/(max(x)-min(x))) + lower))
}

#Calculate the percentile ranks for each entry in a vector
##SOURCED FROM chi: http://stats.stackexchange.com/questions/11924/computing-percentile-rank-in-r ##
perc.rank <- function(x) trunc(rank(x))/length(x)

## Functions to compute difference in months, SOURCED FROM: http://stackoverflow.com/questions/1995933/number-of-months-between-two-dates
monnb <- function(d) { 
  lt <- as.POSIXlt(as.Date(d, origin="1900-01-01"))
  lt$year*12 + lt$mon
} 
# compute a month difference as a difference between two monnb's
mondf <- function(d1, d2) { monnb(d2) - monnb(d1) }
``` 

Import compiled data
```{r Pull Data, echo = TRUE}
# Import pulled Steam data
raw.data <- fread("./data/CompiledResults.csv", header = T, verbose=T)
setnames(raw.data, c("GameName", "SteamID", "Algorithm", "NPlayers", "PercPlayers", "Accuracy", "Precision_0 ", "Recall_0", "F1_0", "Precision_1", "Recall_1", "F1_1"))

#Declare width, height output settings for pdf plot export
pageSize <- c(8.5, 11) #width, height
pHeight <- pageSize[1] * 2 #apply scaling factor of 2 so graph is less compressed
pWidth <- pageSize[2] * 2 #apply scaling factor of 2 so graph is less compressed
```

Compute Basic Stats
```{r Basic Stats}
data.stats <- raw.data[,list(f1_1_mean=mean(F1_1),
                                           f1_1_min=min(F1_1),
                                           f1_1_q1=quantile(F1_1, .25, na.rm=TRUE),
                                           f1_1_median=quantile(F1_1, .50, na.rm=TRUE),
                                           f1_1_q3=quantile(F1_1, .75, na.rm=TRUE),
                                           f1_1_max=max(F1_1),
                             f1_0_mean=mean(F1_0),
                                           f1_0_min=min(F1_0),
                                           f1_0_q1=quantile(F1_0, .25, na.rm=TRUE),
                                           f1_0_median=quantile(F1_0, .50, na.rm=TRUE),
                                           f1_0_q3=quantile(F1_0, .75, na.rm=TRUE),
                                           f1_0_max=max(F1_0)),
                                     by = Algorithm]
write.csv(x = data.stats, file = "./data/CompiledData_Stats.csv", row.names = FALSE)
```

Melt dataset for ggplot
```{r Melt Data, echo = TRUE}
data.melted <- melt(raw.data, id.vars = c("GameName", "SteamID", "Algorithm"))
```

Create boxplot of F1 (1) and Accuracy scores for each algorithm
```{r Boxplot F1 (1), echo = TRUE}
f1.0.plot <- ggplot(raw.data, aes(x = Algorithm, y = F1_0, fill = Algorithm)) +
  geom_boxplot() + 
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0.4, 1),
                     breaks = seq(0.4, 1, 0.05),
                     label = seq(0.4, 1, 0.05),
                     oob = rescale_none)+
  scale_x_discrete(expand = c(0.01, 0.1)) +
  scale_fill_brewer(palette = "Dark2") + 
  xlab("Algorithm") +
  ylab("F1 Measure (TP = 0)") +
  ggtitle("Boxplot of F1 Measure (TP = 0) by Algorithm") +
  guides(fill = guide_legend(order = 1, title = NULL))+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0, vjust = 1, size = 20), 
        axis.title.x = element_text(vjust = 0, size = 13), axis.title.y = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(size = 12), axis.text.y = element_text(vjust = 0.25, size = 10),
        panel.grid.minor = element_line(color = "gray", size = 0.3), panel.grid.major = element_line(color = "gray", size = 0.3), panel.margin = unit(x = 0.12, "inches"),
        legend.box = "vertical", legend.box.just = "left", legend.position = "left", legend.key = element_blank(), legend.text= element_text(size = 12))

f1.1.plot <- ggplot(raw.data, aes(x = Algorithm, y = F1_1, fill = Algorithm)) +
  geom_boxplot() + 
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     breaks = seq(0, 1, 0.05),
                     label = seq(0, 1, 0.05),
                     oob = rescale_none)+
  scale_x_discrete(expand = c(0.01, 0.1)) + 
  scale_fill_brewer(palette = "Dark2") +
  xlab("Algorithm") +
  ylab("F1 Measure (TP = 1)") +
  ggtitle("Boxplot of F1 Measure (TP = 1) by Algorithm") +
  guides(fill = guide_legend(order = 1, title = NULL))+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0, vjust = 1, size = 20), 
        axis.title.x = element_text(vjust = 0, size = 13), axis.title.y = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(size = 12), axis.text.y = element_text(vjust = 0.25, size = 10),
        panel.grid.minor = element_line(color = "gray", size = 0.3), panel.grid.major = element_line(color = "gray", size = 0.3), panel.margin = unit(x = 0.12, "inches"),
        legend.box = "vertical", legend.box.just = "left", legend.position = "left", legend.key = element_blank(), legend.text= element_text(size = 12))

accuracy.plot <- ggplot(raw.data, aes(x = Algorithm, y = Accuracy, fill = Algorithm)) +
  geom_boxplot() + 
  scale_y_continuous(expand = c(0, 0),
                     limits = c(40, 100),
                     breaks = seq(40, 100, 5),
                     label = seq(40, 100, 5),
                     oob = rescale_none)+
  scale_x_discrete(expand = c(0.01, 0.1)) + 
  scale_fill_brewer(palette = "Dark2") +
  xlab("Algorithm") +
  ylab("Accuracy") +
  ggtitle("Boxplot of Accuracy by Algorithm") +
  guides(fill = guide_legend(order = 1, title = NULL))+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0, vjust = 1, size = 20), 
        axis.title.x = element_text(vjust = 0, size = 13), axis.title.y = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(size = 12), axis.text.y = element_text(vjust = 0.25, size = 10),
        panel.grid.minor = element_line(color = "gray", size = 0.3), panel.grid.major = element_line(color = "gray", size = 0.3), panel.margin = unit(x = 0.12, "inches"),
        legend.box = "vertical", legend.box.just = "left", legend.position = "left", legend.key = element_blank(), legend.text= element_text(size = 12))

pdf(file = paste("./analysis/",
                 "F1_Accuracy_Boxplots",
                 ".pdf", sep = ""),
    width = pWidth, height = pHeight, compress = FALSE)
Multiplot(f1.0.plot, f1.1.plot, accuracy.plot, cols = 1)
graphics.off()
```

Plot s scatterplot with linear regression though it and output regression coeffcients
```{r Regression Scatterplot}
linear.reg <- ggplot(raw.data, aes(x = NPlayers, y = F1_1, color = Algorithm)) +
  geom_point(shape = 1) +
  geom_smooth(method = glm, se = FALSE) + 
  facet_grid(Algorithm ~ .) + 
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     breaks = seq(0, 1, 0.05),
                     label = seq(0, 1, 0.05),
                     oob = rescale_none)+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0, 1600),
                     breaks = seq(0, 1600, 50),
                     label = seq(0, 1600, 50),
                     oob = rescale_none)+
  xlab("Number of Players in Test Set") +
  ylab("F1 Measure (TP = 1)") +
  ggtitle("Scatterplot of F1 Measure (TP = 1) for each Algorithm with Linear Regression Line") +
  guides(color = guide_legend(order = 1, title = NULL))+
  theme_bw()+
  theme(plot.title = element_text(hjust = 0, vjust = 1, size = 20), 
        axis.title.x = element_text(vjust = 0, size = 13), axis.title.y = element_text(hjust = 0.5, size = 13),
        axis.text.x = element_text(size = 12), axis.text.y = element_text(vjust = 0.25, size = 10),
        panel.grid.minor = element_line(color = "gray", size = 0.3), panel.grid.major = element_line(color = "gray", size = 0.3), panel.margin = unit(x = 0.12, "inches"),
        legend.box = "vertical", legend.box.just = "left", legend.position = "left", legend.key = element_blank(), legend.text= element_text(size = 12))

pdf(file = paste("./analysis/",
                 "Linear_Regression_F1",
                 ".pdf", sep = ""),
    width = pWidth, height = pHeight, compress = FALSE)
linear.reg
graphics.off()

# Linear Regression (fitting linear curve)
summary(lm(F1_1 ~ NPlayers, raw.data[Algorithm == "Bayes Net"]))
summary(lm(F1_1 ~ NPlayers, raw.data[Algorithm == "Decision Tree"]))
summary(lm(F1_1 ~ NPlayers, raw.data[Algorithm == "kNN (k = 5)"]))
summary(lm(F1_1 ~ NPlayers, raw.data[Algorithm == "Naive Bayes"]))
summary(lm(F1_1 ~ NPlayers, raw.data[Algorithm == "ZeroR"]))

# Log Regression (fitting log curve NOT the classifier)
summary(lm(F1_1 ~ log(NPlayers), raw.data[Algorithm == "Bayes Net"]))
summary(lm(F1_1 ~ log(NPlayers), raw.data[Algorithm == "Decision Tree"]))
summary(lm(F1_1 ~ log(NPlayers), raw.data[Algorithm == "kNN (k = 5)"]))
summary(lm(F1_1 ~ log(NPlayers), raw.data[Algorithm == "Naive Bayes"]))
summary(lm(F1_1 ~ log(NPlayers), raw.data[Algorithm == "ZeroR"]))
```




